- clean: ['~']

- link:
    ~/.config/i3status/config:
      create: true
      path: config/i3status
    ~/.config/i3/config:
      create: true
      path: config/i3
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.xinitrc: xinitrc
    ~/.gitconfig: gitconfig
